# Generated by Django 4.1 on 2022-09-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='terms_conf',
        ),
    ]
